SELECT * FROM movie where title IN (
SELECT DISTINCT TITLE FROM movie 
HAVING COUNT(*) > 1
GROUP BY (TITLE, YEAR))
ORDER BY TITLE, MOVIEID

SELECT DISTINCT TITLE, YEAR FROM movie 
HAVING COUNT(*) > 1
GROUP BY (TITLE, YEAR)
ORDER BY TITLE
